[supervisord]
nodaemon=true
user=root
logfile=/app/logs/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:backend]
command=/app/backend/server
directory=/app/backend
autostart=true
autorestart=true
startsecs=3
startretries=3
stderr_logfile=/app/logs/backend.err.log
stdout_logfile=/app/logs/backend.out.log
environment=GO_ENV="production"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=3
stderr_logfile=/app/logs/nginx.err.log
stdout_logfile=/app/logs/nginx.out.log
